[package]
name = "fankor"
version = "0.1.0"
authors = ["Julio Treviño Páez <julio.tpaez@gmail.com>"]
repository = "https://github.com/juliotpaez/fankor"
license = "Apache-2.0"
description = "Fankor framework to build Solana programs"
edition = "2021"

[features]
library = []
test = ["lazy_static", "parking_lot"]

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
lazy_static = { version = "1.4.0", optional = true }
parking_lot = { version = "0.12.1", optional = true }
solana-program = "1.11.7"
spl-token = { version = "3.5.0", optional = true, features = ["no-entrypoint"] }
fankor-macros = { path = "../fankor-macros" }
fankor-syn = { path = "../fankor-syn" }