[package]
name = "fankor"
version = "0.1.0"
authors = ["Julio Treviño Páez <julio.tpaez@gmail.com>"]
repository = "https://github.com/juliotpaez/fankor"
license = "Apache-2.0"
description = "Fankor framework to build Solana programs"
edition = "2021"

[features]
test = ["lazy_static"]

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
lazy_static = { version = "1.4.0", optional = true }
parking_lot = "0.12.1"
solana-program = "1.11.2"
fankor-macros = { path = "../fankor-macros" }
fankor-syn = { path = "../fankor-syn" }