[package]
name = "fankor"
version = "0.1.0"
authors = ["Julio Treviño Páez <julio.tpaez@gmail.com>"]
repository = "https://github.com/juliotpaez/fankor"
license = "Apache-2.0"
description = "Fancor framework to build Solana programs"
edition = "2021"

[features]
builder-tests = ["lazy_static", "serde", "serde_json"]

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
serde = { version = "1.0.136", optional = true }
serde_json = { version = "1.0.79", optional = true }
fankor-general = { path = "../fankor-general" }
fankor-account = { path = "../fankor-account" }
fankor-constant = { path = "../fankor-constant" }