[package]
name = "fankor"
version = "0.1.0"
authors = ["Julio Treviño Páez <julio.tpaez@gmail.com>"]
repository = "https://github.com/juliotpaez/fankor"
license = "Apache-2.0"
description = "Fankor framework to build Solana programs"
edition = "2021"

[features]
library = []
token-program = ["spl-token", "spl-associated-token-account"]
metadata-program = ["mpl-token-metadata"]
test = ["lazy_static", "parking_lot"]

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
lazy_static = { version = "1.4.0", optional = true }
parking_lot = { version = "0.12.1", optional = true }
sha2 = "0.10.6"
solana-program = "1.14.8"
spl-associated-token-account = { version = "1.1.1", optional = true, features = ["no-entrypoint"] }
spl-token = { version = "3.5.0", optional = true, features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.4.3", optional = true, features = ["no-entrypoint"] }
time = "=0.3.15"
fankor-macros = { path = "../fankor-macros" }