[package]
name = "fankor-syn"
version = "0.1.0"
authors = ["Julio Treviño Páez <julio.tpaez@gmail.com>"]
repository = "https://github.com/juliotpaez/fankor"
license = "Apache-2.0"
description = "Fankor utilities for macros"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.36"
quote = "1.0.17"
serde = { version = "1.0.136", features = ["derive"] }
solana-program = "1.10.5"
syn = { version = "1.0.90", features = ["full"] }
toml = "0.5.0"